import Head from "next/head";
import HomeStart from "./components/Home/HomeStart";
import HomeGetStarted from "./components/HomeGetStarted/HomeGetStarted";
import HomeHeader from "./components/HomeHeader/HomeHeader";
import IndustrySegments from "./components/IndustrySegemts/IndustrySegments";
import Navbar from "./components/Navbar/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CollabAct</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeStart></HomeStart> */}
      <div className="sticky top-0 z-10 bg-white">
        <Navbar />
      </div>
      <HomeHeader />
      <HomeGetStarted />
      <IndustrySegments />
    </div>
  );
}
