import Head from 'next/head'
import HomeStart from './components/Home/HomeStart'
import Navbar from './components/Navbar/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CollabAct</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeStart></HomeStart> */}
      <Navbar />
    </div>
  )
}
